### ISSUE TITLE
Uncaught TypeError: panner.setVelocity is not a function

### ISSUE THREAD

**Issue by KnIfER** [notthetup/birds#4]
CHROME:

Uncaught TypeError: panner.setVelocity is not a function
    at bird.set [as velocity] (bird.js:69)
    at chirp ((index):128)
    at (index):44
    at Value.updateBind (xgui.js:222)
    at Knob.mouseUp (xgui.js:1446)
    at onMouseUp (xgui.js:165)
    at HTMLDocument.<anonymous> (xgui.js:65)

**Comment by notthetup** [comment]
Good catch. Looks like `setVelocity` was removed from the spec.

https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/setVelocity

Will need to think about how we should deal with this. Any ideas?

**Comment by notthetup** [comment]
> The right way to do a Dopper effect in Web Audio would essentially be like
physical modelling - put in a delay node, and animate the delayTime based
on the motion of the object (that is, make the delayTime equate to the
distance of the source from the "ears", and use AudioParams to smoothly
interpolate between values). That would not only provide a physically
accurate Doppler effect, it would work on all nodes.

https://github.com/WebAudio/web-audio-api/issues/372#issuecomment-250024610

**Comment by notthetup** [comment]
I fixed it for now by removing doppler support.
